gameStash/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
  path('', views.Home.as_view(), name='home'),
  path('about/', views.about, name='about'),
  path('games/', views.game_index, name='game-index'),
  path('games/<int:game_id>/', views.game_detail, name = 'game-detail'),
  path('games/create/', views.GameCreate.as_view(), name='game-create'),
  path('games/<int:pk>/update/', views.GameUpdate.as_view(), name='game-update'),
  path('games/<int:pk>/delete/', views.GameDelete.as_view(), name='game-delete'),
  path('games/<int:game_id>/add-play/', views.add_play,  name='add-play'),
  path('accounts/signup/', views.signup, name='signup'),

]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.
class Game(models.Model):
  name = models.CharField(max_length=100)
  genre = models.CharField(max_length=100)
  description = models.TextField()
  console = models.CharField(max_length=100)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.name
  
  def get_absolute_url(self):
    return reverse('game-detail', kwargs={'game_id': self.id})

class Play(models.Model):
  date = models.DateField('Last game-play')

  note = models.TextField()

  game = models.ForeignKey(Game, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.note} on {self.date}"
  class Meta:
    ordering = ["-date"]

main_app/forms.py
from django import forms
from .models import Play


class PlayForm(forms.ModelForm):
  class Meta:
    model = Play
    fields = ['date', 'note']
    widgets = {
      'date': forms.DateInput(
        format=('%Y-%m-%d'),
        attrs={
          'placeholder': 'Select a date',
          'type': 'date'
        }
      ),
    }

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Game , Play
from .forms import PlayForm
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class Home(LoginView):
    template_name = 'home.html'


def about(request):
  return render(request, 'about.html')

@login_required
def game_index(request):
  games = Game.objects.filter(user=request.user)
  games = request.user.game_set.all()
  return render(request, 'games/index.html', {'games': games})

@login_required
def game_detail(request, game_id):
  game = Game.objects.get(id=game_id)

  plays = Play.objects.all()

  play_form = PlayForm()
  return render(request, 'games/detail.html', {'game':game, 'play_form': play_form, 'plays': plays})



class GameCreate(LoginRequiredMixin, CreateView):
  model = Game
  fields = '__all__'

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class GameUpdate(LoginRequiredMixin, UpdateView):
  model = Game
  fields = ['genre', 'description', 'console']

class GameDelete(LoginRequiredMixin, DeleteView):
  model = Game
  success_url ='/games/'

def add_play(request, game_id):
  form =PlayForm(request.POST)
  if form.is_valid():
    new_play = form.save(commit=False)
    new_play.game_id = game_id
    new_play.save()
  return redirect('game-detail', game_id=game_id)



def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('game-index')
        else: 
            error_message = 'Invalid sign up -try again.'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %} 
{% block content %}
<h1>About GameStash</h1>
<hr />
<p class="page-content">
  One of the best ways to reduce stress, enjoy personal time, spend time with friends, expand your creativity and so much more is with playing video games! With a wide selection of genres theres games for everyone. GameStash is the place to track the games you play, on which console, your progress,game details and in game goals. If you're anything like me you play when you can and sometimes that means months between gaming sessions. Let GameStash be the place you keep track of it all!
</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="color-scheme" content="light dark" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.purple.min.css"
    />
    <title>GameStash</title>
    {% block head %} {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <a href="/">
          <img src="" alt="The GameStash Logo" />
        </a>
      </div>
      <nav>
        <ul>
          {% if user.is_authenticated %}
            <li><a href="{% url 'game-index'%}">GameStash</a></li>
            <li><a href="{% url 'game-create' %}">Add a Game</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li>
              <form id="logout-form" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit">Log out</button>
              </form>
            </li>
          {% else %}
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'home' %}">Login</a></li>
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>

main_app/templates/games/detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}

{% endblock %} 
{% block content %}
<section class="container">
    <article class="card">
      <div class="card-content">
        <div class="card-img-container">
        </div>
        <h2 class="card-title">{{ game.name }}</h2>
        <p>A {{ game.genre }}</p>
        <p>{{ game.description }}</p>
        <p>Console I play on:{{game.console}}</p>
      </div>
      <div class="cat-actions">
    <a href="{% url 'game-update' game.id %}" class="btn warn">Edit</a>
    <a href="{% url 'game-delete' game.id %}" class="btn danger">Delete</a>
      </div>
    </article>
  </div>
</section>

<div class="container">
  <section class="plays">
    <h2>Add a Play</h2>
    <form 
      action="{% url 'add-play' game.id %}"
      method="post" 
      class="subsection-content" 
      autocomplete="off"
    >
      {% csrf_token %} 
      {{ play_form.as_p }}
      <button type="submit" class="btn submit">Add Play</button>
    </form>

    <h2>Plays</h2>
    {% if game.play_set.all.count %}
    {% for play in game.play_set.all%}
    
    <div class="container">
      <h4>Date:</h4>
      <td>{{play.date}}</td>

      <h4>Note:</h4>
      <td>{{play.note}}</td>

    </div>
    {% endfor %}
    {% else %}
    <div class="subsection-content">
      <p>⚠️  no plays!</p>
    </div>
  {% endif %}

  </section>
</div>
{% endblock %}

main_app/templates/games/index.html
{% extends 'base.html' %} {% load static %} {% block head %}

{% endblock %} {% block content %}

<section class="page-header">
  <h1>Game List</h1>

</section>

<section class="card-container">
  {% for game in games %}
  <article>
    <a href="{% url 'game-detail' game.id %}">
    <div class="card-content">
      <h2 class="card-title">{{ game.name }}</h2>
      
    </div>
    </a>
  </article>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {% load static %} {% block head %}
  
{% endblock %}

  {% block content %} 
<h1>Welcome to GameStash</h1>

{% if not user.is_authenticated %}

<section class='container'>
  <form action="{% url 'home' %}" method="post" class="login">
    <h1>Login</h1>
    {% csrf_token %} {{ form.as_p }}
    <input type="hidden" name="next" value="{{ next }}" />
    <button type="submit" class="btn submit">Login</button>
  </form>
</section>

{% endif %}

{%  endblock %}

main_app/templates/main_app/game_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Game?</h1>
  
</div>

<h2>Are you sure you want to delete {{ game.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'game-detail' game.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/game_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}

<div class="page-header">
  {% if game %}
    <h1>Edit {{ game.name }}</h1>
  {% else %}
    <h1>Add a Game</h1>
  {% endif %}

</div>

<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
  
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}